version: '3.8'
services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_user_password
      MYSQL_DATABASE: name_your_wordpress_database
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_user_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wordpress-network

  wordpress:
    build:
      context: ./wordpress
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_user_password
      WORDPRESS_DB_NAME: name_your_wordpress_database
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql_db
    networks:
      - wordpress-network

volumes:
  mysql-data:

networks:
  wordpress-network:

