apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-ecommerce
  labels:
    app: mysql-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-ecommerce
  template:
    metadata:
      labels:
        app: mysql-ecommerce
    spec:
      containers:
        - name: database
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found" # Corrected the syntax
          envFrom:
            - secretRef: # Corrected the indentation and syntax
                name: wp-db-secrets
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-volume
